name: Docker

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env: # Global ENV - REGISTRY is fine here
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    env: # Job-level ENV - This is where lower() should correctly work
      # This variable will now hold the lowercased repo name for Docker compatibility
      LOWERCASE_REPO_NAME: ${{ lower(github.repository) }} # <-- This should be lowercase now

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- DEBUG STEP 1 ---
      - name: Debug - Print Calculated Lowercase Image Name
        run: |
          echo "DEBUG: Original github.repository: ${{ github.repository }}"
          echo "DEBUG: Calculated LOWERCASE_REPO_NAME: ${{ env.LOWERCASE_REPO_NAME }}"
          echo "DEBUG: Full Image Path for Metadata: ${{ env.REGISTRY }}/${{ env.LOWERCASE_REPO_NAME }}"
          echo "DEBUG: github.actor (for login): ${{ github.actor }}" # This is usually already lowercase

      # Install the cosign tool except on PR
      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@59acb6260d9c0ba8f4a2f9d9b48431a222b68e20 #v3.5.0
        with:
          cosign-release: 'v2.2.4'

      # Set up BuildKit Docker container builder
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      # Login against a Docker registry except on PR
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }} # github.actor is automatically lowercase for GHCR login
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
        with:
          # Use the already calculated lowercase image name
          images: ${{ env.REGISTRY }}/${{ env.LOWERCASE_REPO_NAME }} # <-- This uses the already lowercased variable
          tags: |
            type=raw,value=${{ github.sha }},enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
            type=ref,event=branch
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{major}}
            type=schedule,pattern={{date 'YYYYMMDD'}}
            type=sha,format=long,prefix=sha-
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
            type=raw,value=${{ github.ref_name }}

      # Build and push Docker image
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # --- DEBUG STEP 2 (Optional, but good for verification) ---
      - name: Debug - Verify Image Tags and Digest
        run: |
          echo "DEBUG: Image tags generated by metadata-action: ${{ steps.meta.outputs.tags }}"
          echo "DEBUG: Image digest from build-push-action: ${{ steps.build-and-push.outputs.digest }}"

      # Sign the published Docker image
      - name: Sign the published Docker image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # --- DEBUG STEP 3 ---
      - name: Debug - Test Image Path for Run Command
        run: |
          echo "DEBUG: Image path for docker run: ${{ env.REGISTRY }}/${{ lower(github.repository) }}:main"

      - name: test
        # Direct use of lower() in a 'run' command should work here too.
        run: docker run ${{ env.REGISTRY }}/${{ lower(github.repository) }}:main
